repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: debug-statements

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.4
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
        exclude: ^src/mcp_oauth_lib/
      - id: ruff-format
        exclude: ^src/mcp_oauth_lib/

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.13.0
    hooks:
      - id: mypy
        args: [--strict]
        exclude: ^(tests/|src/|test_.*\.py)
        additional_dependencies:
          - types-requests
          - fastapi
          - pydantic
          - httpx
          - python-dotenv
          - authlib
